# curl --location 'http://localhost:8080/tasks/enqueue'
#--header 'Content-Type: application/json'
#--data-raw '{
#  "tasks" : [
#    {
#      "taskType" : "SendEmail",
#      "payload": {
#        "sendTo" : ["helloworld@test.com", "helloWorld2@test.com"],
#        "sendFrom": "hello1@test.com",
#        "subject" : "Hi !",
#        "body" : "hope you are well"
#      }
#    },
#    {
#      "taskType" : "GenerateReport",
#      "priority" : 1,
#      "payload" : {
#        "notify" : ["helloworld@test.com", "helloWorld2@test.com"],
#        "reportType" : "Financial Report"
#      }
#    },
#    {
#      "taskType" : "CPUProcess",
#      "priority" : 1,
#      "payload" : {
#        "ProcessType" : "want to fail"
#      },
#      "backOffDuration" : "5s"
#    }
#  ]
#}'
POST http://localhost:8080/tasks/enqueue
Content-Type: application/json

{
  "tasks": [
    {
      "taskType": "SendEmail",
      "payload": {
        "sendTo": [
          "helloworld@test.com",
          "helloWorld2@test.com"
        ],
        "sendFrom": "hello1@test.com",
        "subject": "Hi !",
        "body": "hope you are well"
      }
    },
    {
      "taskType": "GenerateReport",
      "priority": 1,
      "payload": {
        "notify": [
          "helloworld@test.com",
          "helloWorld2@test.com"
        ],
        "reportType": "Financial Report"
      }
    },
    {
      "taskType": "CPUProcess",
      "priority": 1,
      "payload": {
        "ProcessType": "want to fail"
      },
      "backOffDuration": "5s"
    }
  ]
}

###

